### ISSUE TITLE
[Question] 2 Misc sections in readme - why?

### ISSUE THREAD

**Issue by rowild** [aimeos/map#4]
there are 2 misc sections in the readme listing a various amount of functions, 5 of which seem to be the same in each. Is there a reason for that? Can those 2 "Misc" sections be merged to 1 only?

**Comment by aimeos** [comment]
Thank you, the "Misc" sections were exactly the same which may have been caused by a merge from dev-master and the duplicate one has been removed now. At Github pages, the change is visible too now so everything should be OK now and I close the ticket.
